  site: gcodaily
  title: gcodaily
  description:
  googlewebfonts: Fira+Code:wght@400;500;700
  lang: en-US
  timezone: seoul
  repo: https://github.com/p0wex/p0wex.github.io # site repo [optional]
  data-theme: dark # default theme "dark" | "light"

  author:
  name: p0wex
  bio: 
  username: p0wex # general username
  github: gcodaily # github username
  twitter: gcodaily # twitter username
  email: gcodaily@gmail.com

# URL settings
url: "0gunkim.github.io" #
baseurl: # leave blank if not wishd
permalink: "p0wex.github.io/"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->", "<!---", "--->"]
  ignore:
    envs: all

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false
